AWSTemplateFormatVersion: 2010-09-09
Description: IAM role for Wavefront AWS Integration
Parameters:
  ExternalId:
    Description: >-
      External ID for the Wavefront role 
    Type: String
  IAMRoleName:
    Description: Customize the name of IAM role for Wavefront AWS integration
    Type: String  
    Default: WavefrontIntegrationRole
  WavefrontAWSAccountId:
    Description: >-
      Wavefront AWS account ID allowed to assume the integration IAM role. DO NOT CHANGE!
    Type: String
  WavefrontPolicy:
    Description: >-
      policy requirement
    Type: String
    Default: "arn:aws:iam::aws:policy/ReadOnlyAccess"
Resources:
  WavefrontIntegrationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub
                - 'arn:aws:iam::${WavefrontAWSAccountId}:root'
                - { WavefrontAWSAccountId: !Ref WavefrontAWSAccountId}
            Action:
              - 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref ExternalId
      Path: /
      RoleName: !Ref IAMRoleName
      ManagedPolicyArns:
        - !Ref WavefrontPolicy
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Required
      Parameters:
        - ExternalId
        - IAMRoleName
        - WavefrontAWSAccountId
Outputs:
  IAMRoleName:
    Description: AWS IAM Role named to be used with the Wavefront AWS Integration 
    Value: !Ref "WavefrontIntegrationRole"
    Export:
      Name: "Wavefront-IAMRoleName"
